import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | Resume AI Optimizer",
  description: "The terms governing your use of Resume AI Optimizer.",
};

export default function TermsOfServicePage() {
  return (
    <article className="space-y-8">
      <div>
        <h1 className="font-mono text-3xl font-semibold text-foreground mb-2">
          Terms of Service
        </h1>
        <p className="text-sm text-muted-foreground">
          Last updated: 26 July 2026
        </p>
      </div>

      <p className="text-muted-foreground leading-relaxed">
        These Terms of Service (&ldquo;Terms&rdquo;) govern your use of Resume
        AI Optimizer (the &ldquo;Service&rdquo;). By creating an account or
        using the Service, you agree to these Terms. If you do not agree, please
        do not use the Service.
      </p>

      <section className="space-y-3">
        <h2 className="font-mono text-xl font-semibold text-foreground">
          1. What the Service does
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          Resume AI Optimizer analyzes a resume against a job description using
          AI models, and returns an ATS compatibility score, keyword gap
          analysis, rewritten bullet points, and an optional tailored resume
          export. The Service is a productivity and drafting aid — it does not
          guarantee interviews, job offers, or that any specific Applicant
          Tracking System will score your resume identically to our estimate.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-mono text-xl font-semibold text-foreground">
          2. Accounts
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          You must provide accurate information when creating an account and are
          responsible for keeping your login credentials secure. You are
          responsible for all activity that occurs under your account.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-mono text-xl font-semibold text-foreground">
          3. Credits and pricing
        </h2>
        <ul className="list-disc pl-5 space-y-2 text-muted-foreground leading-relaxed">
          <li>New accounts receive a limited number of free scan credits.</li>
          <li>
            Additional credits can be purchased in single or bundled packs at
            the prices shown on the dashboard at the time of purchase.
          </li>
          <li>
            Credits are consumed per resume analysis and do not expire, but are
            non-transferable between accounts.
          </li>
          <li>
            This is a pay-as-you-go credit system, not a recurring subscription
            — you will not be charged automatically after your first purchase.
          </li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-mono text-xl font-semibold text-foreground">
          4. Acceptable use
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          You agree not to: use the Service to process content you do not have
          the right to submit; attempt to bypass credit limits or
          authentication; reverse-engineer or scrape the Service; or use the
          Service in a way that violates applicable law. We may suspend or
          terminate accounts that abuse the Service or attempt to defraud the
          payment system.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-mono text-xl font-semibold text-foreground">
          5. AI-generated content
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          Scores, keyword suggestions, rewritten bullets, and tailored resume
          text are generated by third-party AI models and may contain errors,
          omissions, or inaccuracies. You are responsible for reviewing and
          verifying any AI-generated content before using it in a real job
          application — including confirming that facts, dates, and claims about
          your experience remain accurate.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-mono text-xl font-semibold text-foreground">
          6. Payments
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          Payments are processed by Razorpay. By making a purchase, you also
          agree to Razorpay&rsquo;s applicable terms for payment processing. See
          our{" "}
          <a
            href="/legal/refund"
            className="text-primary underline underline-offset-4"
          >
            Refund &amp; Cancellation Policy
          </a>{" "}
          for details on refunds.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-mono text-xl font-semibold text-foreground">
          7. Intellectual property
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          You retain all rights to the resume content you submit. We claim no
          ownership over your resume or job description text. The Service itself
          — including its design, code, and branding — remains our property and
          may not be copied or redistributed without permission.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-mono text-xl font-semibold text-foreground">
          8. Disclaimer of warranties
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          The Service is provided &ldquo;as is&rdquo; without warranties of any
          kind, express or implied. We do not warrant that the Service will be
          uninterrupted, error-free, or that any particular ATS outcome will
          result from using it.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-mono text-xl font-semibold text-foreground">
          9. Limitation of liability
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          To the maximum extent permitted by law, our total liability for any
          claim arising from your use of the Service is limited to the amount
          you paid us in the twelve months preceding the claim.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-mono text-xl font-semibold text-foreground">
          10. Governing law
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          These Terms are governed by the laws of India, and any disputes will
          be subject to the exclusive jurisdiction of the courts of India.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-mono text-xl font-semibold text-foreground">
          11. Changes to these Terms
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          We may update these Terms from time to time. Continued use of the
          Service after changes take effect constitutes acceptance of the
          revised Terms.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-mono text-xl font-semibold text-foreground">
          12. Contact us
        </h2>
        <p className="text-muted-foreground leading-relaxed">
          Questions about these Terms can be sent to{" "}
          <a
            href="mailto:support@yourdomain.com"
            className="text-primary underline underline-offset-4"
          >
            support gjain7524@gmail.com
          </a>
          .
        </p>
      </section>
    </article>
  );
}
